# Generated by Django 3.1.2 on 2020-11-02 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_auto_20201102_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='typeOfLeave',
        ),
    ]
