# Generated by Django 3.1.2 on 2020-11-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_remove_application_typeofleave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='recommended',
        ),
        migrations.RemoveField(
            model_name='application',
            name='recommended_by',
        ),
        migrations.RemoveField(
            model_name='application',
            name='recommender_comments',
        ),
    ]
