# Generated by Django 3.1.2 on 2020-11-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_auto_20201102_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='typeOfLeave',
            field=models.CharField(choices=[('EL', 'Earned Leave'), ('HPL', 'Half Pay Leave'), ('OT', 'Other Leave')], default='OT', max_length=3),
        ),
    ]
